//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RP.rc
//
#define IDD_ABOUTBOX                    100
#define CG_IDD_CONTROLBAR               102
#define CG_ID_VIEW_CONTROLBAR           103
#define IDS_REGISTRY_COMPANY            104
#define IDS_ACADPATH_KEY                105
#define IDS_ACADPATH_VALUENAME          106
#define IDS_OPENFILE_ERROR              107
#define IDR_MAINFRAME                   128
#define IDR_RPTYPE                      129
#define IDR_RPTYPE2D                    129
#define IDR_APPCHILD1                   129
#define IDR_RPTYPE3D                    130
#define IDR_APPCHILD2                   130
#define IDR_APPCHILD3                   131
#define IDI_ICON2D                      132
#define IDR_APPCHILD4                   132
#define IDR_APPCHILD5                   133
#define IDI_ICON3D                      134
#define IDR_APPCHILD6                   134
#define IDI_GATEOFF                     135
#define IDR_APPCHILD7                   135
#define IDI_GATEON                      136
#define IDR_APPCHILD8                   136
#define IDD_AXIS_AJUST_DLG              137
#define IDD_ZEROAJUST_DLG               137
#define IDD_PARAMDLG                    139
#define IDD_PARAM_GENERAL               139
#define IDD_CARD_TEST_DLG               146
#define IDD_POS_REC_DLG                 147
#define IDD_PARAM_GRAPHIC               148
#define IDD_PARAM_VIEW_GENERAL          150
#define IDD_COLORBTN                    151
#define IDD_PROPERTY_SPACE              152
#define IDD_PROPERTY_LAYER              153
#define IDD_PARAM_VIEW2D_EACH           154
#define IDD_PARAM_VIEW_LINE             154
#define IDD_PARAM_VIEW_COLOR            154
#define IDI_ICON1                       157
#define IDD_DIALOG1                     158
#define IDD_PARAM_SYSTEM                158
#define IDD_PARAM_VIEW_FILL             159
#define IDD_PARAM_VIEW_RENDER           159
#define IDD_PARAM_VIEW_RENDER1          159
#define IDD_PARAM_VIEW_RENDER2          160
#define IDB_IMAGELIST                   164
#define IDD_PARAM_DRIVER                165
#define IDD_FILE_ADD                    166
#define IDD_DRIVER_ADD                  167
#define IDD_PARAM_DRIVER_NEW            168
#define IDD_DRIVER_MANAGE               168
#define IDD_DRIVER_ADD_NEW              169
#define IDD_DRIVER_EDIT                 169
#define IDB_BITMAP2                     170
#define IDB_DISABLED                    170
#define IDB_NORMAL                      172
#define IDC_AXISNAME                    1003
#define IDC_LAYERINDEX                  1004
#define IDC_POSX                        1004
#define IDC_POSY                        1005
#define IDC_LAYERSPIN                   1005
#define IDC_POSZ                        1006
#define IDC_AXISNAME2                   1006
#define IDC_SCAN_CONTOUR                1006
#define IDC_SCAN_PARALLEL               1007
#define IDC_VELX                        1008
#define IDC_LAYERZ                      1008
#define IDC_SCAN_PARALLEL_CONTOUR       1008
#define IDC_SCAN_CONTOUR_PARALLEL       1009
#define IDC_VELY                        1009
#define IDC_TREE_VIEW                   1009
#define IDC_AXISNAME3                   1009
#define IDC_VELZ                        1010
#define IDC_POS1                        1010
#define IDC_POS2                        1011
#define IDC_ACCX                        1012
#define IDC_POS3                        1012
#define IDC_ACCY                        1013
#define IDC_SETHOME                     1013
#define IDC_ACCZ                        1014
#define IDC_POS4                        1014
#define IDC_BAKTOHOME                   1015
#define IDC_BAK_TO_HOME                 1015
#define IDC_FBACKX                      1016
#define IDC_POS5                        1016
#define IDC_FBACKY                      1017
#define IDC_POS6                        1017
#define IDC_FBACKZ                      1018
#define IDC_START                       1018
#define IDC_START_PROFILE               1018
#define IDC_EDIT1                       1019
#define IDC_DELTAX                      1019
#define IDC_SCALE                       1019
#define IDC_ZOOM_SCALE                  1019
#define IDC_ROTATE_X                    1019
#define IDC_RANGE_X                     1019
#define IDC_LIGHT_POS_X                 1019
#define IDC_FILENAME                    1019
#define IDC_CURRENT                     1019
#define IDC_HOMEX                       1020
#define IDC_STOP_PROFILE                1020
#define IDC_RANGE_Y                     1020
#define IDC_CNC_LEN_MIN                 1020
#define IDC_LIGHT_POS_Y                 1020
#define IDC_HOMEY                       1021
#define IDC_CURRENT_OPERATION           1021
#define IDC_RANGE_Z                     1021
#define IDC_LIGHT_POS_Z                 1021
#define IDC_ZOOM_SCALEZ                 1021
#define IDC_HOMEZ                       1022
#define IDC_LAYERNUM                    1022
#define IDC_MAT_SHININESS               1022
#define IDC_GS_CLEAR_X                  1023
#define IDC_ENTNUM                      1023
#define IDC_RESET_CORD                  1023
#define IDC_STARTX                      1024
#define IDC_STATIC_X                    1024
#define IDC_LOOPNUM                     1024
#define IDC_STARTY                      1025
#define IDC_STATIC_Y                    1025
#define IDC_ROTATE_Y                    1025
#define IDC_NCENTNUM                    1025
#define IDC_STARTZ                      1026
#define IDC_STATIC_Z                    1026
#define IDC_ROTATE_Z                    1026
#define IDC_GS_CLEAR_Y                  1027
#define IDC_TRANSLATE_X                 1027
#define IDC_STOPX                       1028
#define IDC_STATIC_GATEOFF              1028
#define IDC_SCALE_XYZ                   1028
#define IDC_STATIC_GATE                 1028
#define IDC_STOPY                       1029
#define IDC_TRANSLATE_Y                 1029
#define IDC_STOPZ                       1030
#define IDC_DELTAY                      1031
#define IDC_NOWPOS_X                    1032
#define IDC_NOWPOS_Y                    1033
#define IDC_DSTPOS_X                    1035
#define IDC_DSTPOS_Y                    1036
#define IDC_CENTER_X                    1038
#define IDC_GSFBACKX                    1039
#define IDC_GSFBACKY                    1040
#define IDC_CENTER_Y                    1041
#define IDC_IPOL_RATE                   1043
#define IDC_IPOL_LINE                   1044
#define IDC_IPOL_ARC_CW                 1045
#define IDC_IPOL_ARC_CCW                1046
#define IDC_IO_WRITE0                   1047
#define IDC_IO_WRITE1                   1048
#define IDC_IOREAD                      1049
#define IDC_IOREAD1                     1049
#define IDC_IOREAD2                     1050
#define IDC_IPOL_STOP                   1051
#define IDC_IPOL_PAUSE                  1052
#define IDC_IPOL_RESUME                 1053
#define IDC_POS_REC                     1054
#define IDC_CLEAR                       1054
#define IDC_BKCOLOR                     1054
#define IDC_COLOR                       1054
#define IDC_REGION                      1055
#define IDC_FVEL_XY                     1055
#define IDC_GSVEL_X                     1056
#define IDC_SHOW_VALUES                 1056
#define IDC_SCALE_SPIN                  1057
#define IDC_GSVEL_Y                     1057
#define IDC_GSVEL_XY                    1058
#define IDC_VEL                         1059
#define IDC_FVEL_X                      1059
#define IDC_STOP                        1059
#define IDC_AJUST_CENTER_ET             1060
#define IDC_FVEL_Y                      1060
#define IDC_OFFSET_DIST                 1061
#define IDC_FVELZ                       1061
#define IDC_CNC_LINE_DIST               1062
#define IDC_LAYER_DIST                  1063
#define IDC_GS_CARD_ADDRES              1064
#define IDC_LINEANGLE_DELTA             1064
#define IDC_BJ_CARD_ADDRES              1065
#define IDC_LINEANGLE_FIRST             1065
#define IDC_GS_IRQ                      1066
#define IDC_DIST_O1_O                   1067
#define IDC_VELOCITY                    1069
#define IDC_ACCEL                       1070
#define IDC_IPOL_LINE_VEL               1071
#define IDC_IPOL_ARC_VEL                1072
#define IDC_Z_VEL                       1073
#define IDC_EMULATE_SPLIT_LEN           1074
#define IDC_FREEBACK_INTERVAL           1075
#define IDC_ITIME                       1076
#define IDC_CHECK1                      1077
#define IDC_USE_LIST                    1077
#define IDC_CHECK_SELFX_ON_BUILD_LOOP   1077
#define IDC_FREE_SQ                     1077
#define IDC_WIDTH                       1077
#define IDC_SHOWBJ                      1077
#define IDC_LINE_CROSS                  1077
#define IDC_SCANON_WIDTH                1078
#define IDC_CHECK7                      1078
#define IDC_SHOWGS                      1078
#define IDC_CHECK2                      1079
#define IDC_CHECK_SELFX_AFTER_BUILD_LOOP 1079
#define IDC_RANDOM                      1079
#define IDC_SAMESCALE                   1079
#define IDC_CHECK3                      1080
#define IDC_CHECK_SELFX_AFTER_OFFSET    1080
#define IDC_INVISIBLE                   1080
#define IDC_CHECK4                      1081
#define IDC_AUTO_SAVE_PARAM             1081
#define IDC_CHECK5                      1082
#define IDC_AUTO_LOAD_WMTOOL            1082
#define IDC_CHECK6                      1083
#define IDC_READ_CONTINUE_WHEN_FILE_HAVE_3DENTITY 1083
#define IDC_CHECK_COX_AFTER_OFFSET      1084
#define IDC_CONTOUR_COLOR               1084
#define IDC_TIME_COUNT                  1084
#define IDC_GS_PULSE                    1085
#define IDC_SCANON_COLOR                1086
#define IDC_FREE1                       1086
#define IDC_SCANOFF_COLOR               1087
#define IDC_FREE2                       1087
#define IDC_FREE3                       1088
#define IDC_FREES                       1090
#define IDC_FSQ_HIGH                    1091
#define IDC_FSQ_LOW                     1092
#define IDC_COMBO1                      1093
#define IDC_LIGHT_COLORS                1093
#define IDC_SHOW_KIND                   1093
#define IDC_COMBO2                      1094
#define IDC_MAT_COLORS                  1094
#define IDC_LINE_KIND                   1094
#define IDC_LIGHT_COLOR                 1096
#define IDC_MAT_COLOR                   1097
#define IDC_EDIT2                       1101
#define IDC_TIMERCOUNT                  1101
#define IDC_DRIVER_INFO                 1101
#define IDC_OPENBYCAD_WHEN_FILE_HAVE_3DENTITY 1105
#define IDC_ASSERT_PARAM_ET             1106
#define IDC_DRIVER                      1107
#define IDC_DRIVE_FILE                  1108
#define IDC_DRIVER_NEW                  1109
#define IDC_DRIVER_DEL                  1110
#define IDC_DRIVER_PARAM                1111
#define IDC_DRIVER_DEL2                 1112
#define IDC_DRIVER_ADD                  1112
#define IDC_DRIVER_EDIT                 1113
#define IDC_DRIVER_EDIT2                1114
#define IDC_DRIVER_EDIT_CURRENT         1114
#define IDC_DRIVER_SET                  1115
#define IDC_DRIVE_FILE_ADD              1116
#define IDC_DRIVE_FILE_DEL              1117
#define IDC_DRIVER_FILE_SEL             1118
#define IDC_NODRIVER                    1119
#define IDC_DRIVER_SAVE                 1120
#define IDC_BROWSE                      1120
#define IDC_DRIVER_NAME                 1121
#define IDC_INFO                        1124
#define IDC_DRIVERS                     1125
#define IDC_PARAM                       1126
#define IDC_FILE_NAME                   1127
#define IDC_COLOR1                      5101
#define IDC_COLOR2                      5102
#define IDC_COLOR3                      5103
#define IDC_COLOR4                      5104
#define IDC_COLOR5                      5105
#define IDC_COLOR6                      5106
#define IDC_COLOR7                      5107
#define IDC_COLOR8                      5108
#define IDC_COLOR9                      5109
#define IDC_COLOR10                     5110
#define IDC_COLOR11                     5111
#define IDC_COLOR12                     5112
#define IDC_COLOR13                     5113
#define IDC_COLOR14                     5114
#define IDC_COLOR15                     5115
#define IDC_COLOR16                     5116
#define IDC_COLOR17                     5117
#define IDC_COLOR18                     5118
#define IDC_COLOR19                     5119
#define IDC_COLOR20                     5120
#define IDC_OTHER                       5121
#define ID_FILEEXPORT                   32771
#define ID_SHOW2D                       32774
#define ID_SHOW3D                       32775
#define ID_EMU_PARA                     32779
#define ID_FILECLOSE                    32782
#define ID_PRODUCE                      32783
#define IDM_RESET_CORD                  32786
#define ID_PARAMS                       32788
#define ID_EMULATE                      32795
#define ID_CENTERAJUST                  32804
#define ID_PAUSE                        32811
#define ID_STOP                         32812
#define ID_CARD_TEST                    32819
#define ID_PROPERTY                     32825
#define IDC_POS_WATCH                   32828
#define ID_EMULATE_QUICK                32830
#define ID_VIEW_PARAM                   32831
#define ID_FILE_OPEN_WITH_CAD           32834
#define ID_EMULATE_PAUSE                32835
#define ID_EMULATE_STOP                 32836
#define ID_PRODUCE_PAUSE                32837
#define ID_PRODUCE_STOP                 32838
#define ID_CARD_DEBUG                   32839
#define ID_EXPORT_PUL                   32840
#define IDS_OPENFILE_LIST               57603

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        173
#define _APS_NEXT_COMMAND_VALUE         32841
#define _APS_NEXT_CONTROL_VALUE         1128
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
